export interface Dog {
  Id: number;
  BullyId: number;
  AbkcNo: string;
  UkcNo: string;
  AkcNo: string;
  AdbaNo: string;
  OtherNo: string;
  RegNo: string;
  RegType: string;
  DogName: string;
  Title: string;
  Suffix: string;
  Breed: string;
  Gender: string;
  Color: string;
  SireNo: number | null;
  DamNo: number | null;
  Birthdate: string | null;
  LitterNo: number | null;
  OwnerId: number;
  CoOwnerId: number | null;
  TatooNo: string;
  ChipNo: string;
  Points: number | null;
  ChampPoints: number | null;
  ChampWins: number | null;
  FirstGeneration: boolean;
  Registered: boolean;
  Verified: boolean;
  Printed: boolean;
  Comments: string;
  DateCreated: string | null;
  DateRegistered: string | null;
  RegAmt: number | null;
  RegUser: string;
  Pups: number | null;
  Degrees: string;
  LastModified: string | null;
  ModifiedBy: string;
  bdna: string;
  nw: boolean | null;
  ChcertPrinted: boolean | null;
  BreedingDamOwnerId: number | null;
  BreedingDamCoOwnerId: number | null;
  BreedingSireOwnerId: number | null;
  BreedingSireCoOwnerId: number | null;
  wpPoints: number | null;
  saveBully: boolean | null;
  sabDate: string | null;
  needsNewChcert: boolean | null;
  wpChampWins: number | null;
  needsNewWpchcert: boolean | null;
  wpTitle: string;
  n: boolean | null;
  bb: boolean | null;
  majors: number | null;
  judges: number | null;
  origTitle: string;
  inw: boolean | null;
}
